### ISSUE TITLE
Several workflows but only one produces test results

### ISSUE THREAD

**Issue by kpturner** [EnricoMi/publish-unit-test-result-action#200] opened 2021-12-04 12:59 UTC
I have three workflows.  All three produce unit test results and all three try to publish them with this action.  Only one of them actually publishes anything. The others publish nothing despite showing no errors.   Similarly, when all three workflows run as checks as the result of a push, only one set of results are published, and against a completely random workflow that doesn't even use this action.   Am I missing something specific that needs to be added to the inputs?

**Comment by kpturner** [comment] 2021-12-04 13:01
[logs_1724.zip](https://github.com/EnricoMi/publish-unit-test-result-action/files/7653954/logs_1724.zip)

No errors and no results published

**Comment by EnricoMi** [comment] 2021-12-04 13:30
Do all three actions use the same value for `check_name`? Then they will overwrite each other's results. Use different values there to distinguish between the three workflows and consecutive runs of each of the workflows.

Are your workflows in a public repo so I can take a closer look?

The random workflow is a known issue with GitHubs AP (#12) and out of our control.

**Comment by kpturner** [comment] 2021-12-04 13:39
Oh wow!  Didn't expect such a quick response.   None of them specify `check_name` so they all use the default. I will give that a go thanks.

I found that other issue too.  How annoying :(

**Comment by kpturner** [comment] 2021-12-04 13:52
So I used a unique `check_name` but it didn't seem to help.    I am testing it by starting all three with `workflow_dispatch`.  The workflows run concurrently on a load balanced EC2 instance (maybe that is the issue?).  They each upload their unit tests results as artifacts.  Then a separate job starts on `ubuntu-latest` that downloads the artifacts and publishes them.  

I only get results published for the first one workflow I start.  The other two never produce anything.

 If I change the order that I start them in, then the first one works always, even though it didn't work when it was run second or third.

**Comment by kpturner** [comment] 2021-12-04 14:02
I tried running two workflows and they both ran concurrently, both uploaded uniquely names artifacts, downloaded them, ran this action but produced no output.  Very weird.

**Comment by kpturner** [comment] 2021-12-04 14:21
I have now added the `github.run_id` to the `check_name` and I am now getting results for each one.  They still aren't attached to the right workflow but it is a step in the right direction :)

**Comment by EnricoMi** [comment] 2021-12-04 15:03
Another thing to try is setting the log level for all of the three actions as follows:
```
with:
  log_level: DEBUG
  root_log_level: DEBUG
```
Then lets compare the log output of al three actions (the log zip you added before).

If that does not provide any insights, could you provide the workflow yaml files so I can reproduce it in a public repo? You said they start due to a `workflow_dispatch`, all on the same `workflow_dispatch` event, or do you trigger them individually (three times)?

**Comment by kpturner** [comment] 2021-12-04 15:26
Triggered three times (individually).

I will try this now....

**Comment by kpturner** [comment] 2021-12-04 15:41
Worked
[logs_1737.zip](https://github.com/EnricoMi/publish-unit-test-result-action/files/7654156/logs_1737.zip)
Worked
[logs_1738.zip](https://github.com/EnricoMi/publish-unit-test-result-action/files/7654157/logs_1738.zip)
Says it worked but can't find results anywhere
[logs_1739.zip](https://github.com/EnricoMi/publish-unit-test-result-action/files/7654168/logs_1739.zip)

**Comment by EnricoMi** [comment] 2021-12-04 15:54
Your third action's `check_name` is `check_name: FDEL Unit Test Results$ {{ github.run_id }}`, I think it should be `check_name: FDEL Unit Test Results ${{ github.run_id }}`.

**Comment by EnricoMi** [comment] 2021-12-04 16:08
Do you run the `workflow_dispatch` on master or a branch?

**Comment by EnricoMi** [comment] 2021-12-04 16:18
I have tried to reproduce this in my playground repo [EnricoMi/python](https://github.com/EnricoMi/python). There are two manual trigger workflows: https://github.com/EnricoMi/python/tree/master/.github/workflows

I triggered them to run on master concurrently. You can navigate to the results as follows:
1. go to the commit history of master: https://github.com/EnricoMi/python/commits/master
2. click on the :x:, scroll down to the result tests and click on [Details](https://github.com/EnricoMi/python/runs/4417986274):
![grafik](https://user-images.githubusercontent.com/44700269/144716617-81d9ce23-6899-4fc0-9fd3-10c77e1a0cd7.png)
3. this brings you to the one test result, which may be at a random workflow but all actions' output should be at the same workflow

My two manual workflows have individual `check_name` values but fixed across runs (no `github.run_id`). I would suspect you to find all action results in the same way in your repo.

**Comment by kpturner** [comment] 2021-12-04 17:33
That doesn't really work for me I am afraid - even if it did it is not a very intuitive way to find the test results.  There is no relationship between a manual workflow dispatch and a commit.  I could run a manual workflow dispatch on a branch that has no commits on it at all.   So when I look through the commit history on this branch there is no route to see test results to click on:
![image](https://user-images.githubusercontent.com/308646/144718691-557a3b1c-91c6-4f7f-bd45-a2e3692f9b0b.png)
The only route I know of to seeing test results of a manual workflow is to navigate to that workflow run.  Here are my three that you have logs for
![image](https://user-images.githubusercontent.com/308646/144718782-b2f1d7df-dc08-4eb2-9255-32f70ae0b775.png)

No results here. This was the last one to finish
![image](https://user-images.githubusercontent.com/308646/144718800-9ad81538-579d-4441-8675-bd34a0bade00.png)
This one shows two results of three
![image](https://user-images.githubusercontent.com/308646/144718863-a2c50fe1-d683-4702-a24f-0258d33cb5e6.png)
This one has results that show on the previous run
![image](https://user-images.githubusercontent.com/308646/144718880-5bca89e4-2202-446e-a005-f7c622d41779.png)

So of two runs, I cannot find any results for the one that took the longest to finish.

**Comment by EnricoMi** [comment] 2021-12-04 17:57
Thanks for the images, this is very helpful to see what you see. It is interesting that you do not have any check results behind the commits, see the :heavy_check_mark: behind the "committed 3 days ago":
![grafik](https://user-images.githubusercontent.com/44700269/144719416-f6684a9f-37e9-47a6-a7e1-2746c2f6ddad.png)

An alternative route is the following:
1. click on the commit sha:
![grafik](https://user-images.githubusercontent.com/44700269/144719464-40c2d727-e2b8-423e-bf77-8b775e75889d.png)
2. click on the :heavy_check_mark: before the commit message:
![grafik](https://user-images.githubusercontent.com/44700269/144719493-6d44ee05-3273-44af-8ec6-4766c670d5fb.png)
![grafik](https://user-images.githubusercontent.com/44700269/144719509-d15f3cbf-41ba-4754-92d4-3c5a8607e636.png)

If all this does not work for you, try the following route:
1. Go to your actions
2. Click on a `workflow_dispatch` action run
3. Click on the `Publish Unit Tests Results` job
![grafik](https://user-images.githubusercontent.com/44700269/144719614-3aaca9e2-a8fd-4fdc-b332-3d1b164a083a.png)
4. Remove the `?check_suite_focus=true` from the URL
![grafik](https://user-images.githubusercontent.com/44700269/144719628-6c83fc31-99a2-4af4-b3f3-b6bbe82ea77d.png)
5. You should see all workflows that ran on the same commit as your action

The results should be listed under one of these workflows.

**Comment by kpturner** [comment] 2021-12-04 18:55
Blimey - that is sure convoluted. I did find them that way. Not sure it is the answer my team will want though :D

I am thinking I might try just putting the three runs in a composite action and publish all the results just once.

**Comment by EnricoMi** [comment] 2021-12-04 19:15
You can have the build and test job of all three workflows in one workflow as separate jobs and have a single publish job. That is probably what you meant with composite, but "composite action" means something different in GitHub.

I am glad you found your results. The workflow, runs and check model of GitHub is frustratingly complex. Well, convoluted is really the right term here.

We are all set then?

**Comment by kpturner** [comment] 2021-12-04 21:30
Yes I know what a composite action is :)

I created a single private composite action that does a built/test/upload that accepts an input for the thing it is going to operate on.  So instead of three separate workflows I just have one that calls the composite action for each of the components - then has one single publication job at the end for the whole lot.   It is not ideal, because it is aggregating all the results together. I probably need to give the XML output unique names to work around that (at the moment the XML files are the same name in different folders).

It isn't a great solution but I think we can close this if there is no other way around it.

**Comment by kpturner** [comment] 2021-12-05 09:06
![image](https://user-images.githubusercontent.com/308646/144740447-004c1d6f-393f-4600-930f-5d749444a515.png)

That is a better compromise :)

**Comment by EnricoMi** [comment] 2021-12-05 09:14
You can have three "builds and tests" jobs and have the publish job depend on all three. This way the three jobs run in parallel.

Anyway, glad we could solve the where-are-the-results mystery.

**Closed by EnricoMi** 2021-12-05 09:14 UTC
