### ISSUE TITLE
Fails if run by schedule

### ISSUE THREAD

**Issue by ned14** [EnricoMi/publish-unit-test-result-action#63] opened 2020-12-01 11:35 UTC
https://github.com/ned14/llfio/runs/1477349816?check_suite_focus=true

```
Run EnricoMi/publish-unit-test-result-action@v1.3
  with:
    check_name: Unit Test Results
    github_token: ***
    files: **/merged_junit_results.xml
    log_level: INFO
/usr/bin/docker run --name ac1af7e4c4db2a986807a5c45326c_1a9922 --label 179394 --workdir /github/workspace --rm -e INPUT_CHECK_NAME -e INPUT_GITHUB_TOKEN -e INPUT_FILES -e INPUT_REPORT_INDIVIDUAL_RUNS -e INPUT_DEDUPLICATE_CLASSES_BY_FILE_NAME -e INPUT_LOG_LEVEL -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/llfio/llfio":"/github/workspace" 179394:727ac1af7e4c4db2a986807a5c45326c
Traceback (most recent call last):
  File "/action/publish_unit_test_results.py", line 793, in <module>
    commit = get_var('COMMIT') or get_commit_sha(event, event_name)
  File "/action/publish_unit_test_results.py", line 765, in get_commit_sha
    raise RuntimeError("event '{}' is not supported".format(event))
RuntimeError: event '{'schedule': '0 0 1 * *'}' is not supported
```

**Comment by EnricoMi** [comment] 2020-12-01 12:17
This has been fixed in #58, duplicate of #57. Please use latest version where this should work. Please reopen if it does not.

**Closed by EnricoMi** 2020-12-01 12:17 UTC
