### ISSUE TITLE
Retry if github returns 403 rate limit warning

### ISSUE THREAD

**Issue by jaqx0r** [EnricoMi/publish-unit-test-result-action#150] opened 2021-07-02 07:20 UTC
Please implement a backoff-and-retry when GitHub returns a 403 error.

As seen in https://github.com/google/mtail/runs/2969598960?check_suite_focus=true

```
Traceback (most recent call last):
  File "/action/publish_unit_test_results.py", line 91, in <module>
    main(settings)
  File "/action/publish_unit_test_results.py", line 32, in main
    Publisher(settings, gh).publish(stats, results.case_results)
  File "/action/publish/publisher.py", line 64, in publish
    pull = self.get_pull(self._settings.commit)
  File "/action/publish/publisher.py", line 80, in get_pull
    self._logger.debug('found {} pull requests for commit {}'.format(issues.totalCount, commit))
  File "/usr/local/lib/python3.6/site-packages/github/PaginatedList.py", line 154, in totalCount
    "GET", self.__firstUrl, parameters=params, headers=self.__headers
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 319, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: 403 {"documentation_url": "https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#abuse-rate-limits", "message": "You have triggered an abuse detection mechanism. Please wait a few minutes before you try again."}
```

**Comment by EnricoMi** [comment] 2021-07-04 16:58
This is annoying, thanks for raising this. Problematic is that 403 means "Forbidden", which is not retryable. But the type of exception seems to give a good indication that this is something to retry later. Let me try to sketch out a solution.

**Comment by EnricoMi** [comment] 2021-07-04 20:40
@jaqx0r it would we interesting to understand what caused the rate limit exceeded in the first place? Do you see this issue regularily? Is this caused by the [rate limit of your token](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting) or by the [abuse rate limit](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#abuse-rate-limits). The exception message implies the latter.

Maybe in addition retrying those exceptions with some backoff, the action should also throttle down its requests in general to avoid the abuse rate limit. Maybe this is caused by other actions using the same toking as they run in the same workflow.

**Comment by EnricoMi** [comment] 2021-07-05 14:14
The action sends requests to GitHub API as quickly as possible. This seems to trigger the abuse rate limit which caused the exception in the first place. I have added a throttling so that `GET` requests are at least 0.25 seconds apart and write requests 2.0 seconds apart (both used to be less than 0.01 seconds). This should avoid the rate abuse error. I will try to get this logic moved upstream into the PyGitHub client.

Please test this fix by using:

    uses: EnricoMi/publish-unit-test-result-action/composite@master

Please let me know if the default throttling settings are still insufficient to avoid abuse rate limits.

I agree that the above exception should be retried, but that should also be done by the PyGitHub client, as there is already code that identifies that situation, as well as urllib already considering `retry-after` header values.

**Comment by EnricoMi** [comment] 2021-07-07 15:18
Released with latest v1 release v1.19:

    uses: EnricoMi/publish-unit-test-result-action@v1

**Closed by EnricoMi** 2021-07-07 15:18 UTC

**Comment by jaqx0r** [comment] 2021-08-01 00:06
Thanks!

**Comment by dan-ih** [comment] 2024-04-04 14:44
This seems to be happening still in 2.4.2, but probably because we are running many of these publish-unit-test-result-actions in parallel. Backoff/retry logic for 403s would be really helpful.

**Comment by EnricoMi** [comment] 2024-04-05 07:11
Can you share some logs please?

**Comment by jaqx0r** [comment] 2024-04-22 14:28
I just got a run failure with a 403:

```
Run docker://ghcr.io/enricomi/publish-unit-test-result-action:v1.6
  with:
    commit: 6b[2](https://github.com/google/mtail/actions/runs/8785762325/job/24107012013#step:5:2)417ba04c557b7e2d108fe0b0[3](https://github.com/google/mtail/actions/runs/8785762325/job/24107012013#step:5:3)e6ab0435ea84
    check_name: Unit Test Results
    github_token: ***
    files: **/test-results/**/*.xml
/usr/bin/docker run --name ghcrioenricomipublishunittestresultactionv16_15113e --label 195ee0 --workdir /github/workspace --rm -e "INPUT_COMMIT" -e "INPUT_CHECK_NAME" -e "INPUT_GITHUB_TOKEN" -e "INPUT_FILES" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/mtail/mtail":"/github/workspace" ghcr.io/enricomi/publish-unit-test-result-action:v1.6
202[4](https://github.com/google/mtail/actions/runs/8785762325/job/24107012013#step:5:4)-04-22 14:24:38 +0000 - publish-unit-test-results -  INFO - reading **/test-results/**/*.xml: ['test-results/test-output.xml']
2024-04-22 14:24:38 +0000 - publish.publisher -  INFO - publishing results for commit 6b2417ba04c[5](https://github.com/google/mtail/actions/runs/8785762325/job/24107012013#step:5:5)57b7e2d108fe0b03e6ab0435ea84
2024-04-22 14:24:38 +0000 - publish.publisher -  INFO - creating check
Traceback (most recent call last):
  File "/action/publish_unit_test_results.py", line 91, in <module>
    main(settings)
  File "/action/publish_unit_test_results.py", line 32, in main
    Publisher(settings, gh).publish(stats, results.case_results)
  File "/action/publish/publisher.py", line [6](https://github.com/google/mtail/actions/runs/8785762325/job/24107012013#step:5:6)4, in publish
    pull = self.get_pull(self._settings.commit)
  File "/action/publish/publisher.py", line 80, in get_pull
    self._logger.debug('found {} pull requests for commit {}'.format(issues.totalCount, commit))
  File "/usr/local/lib/python3.6/site-packages/github/PaginatedList.py", line 154, in totalCount
    "GET", self.__firstUrl, parameters=params, headers=self.__headers
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 319, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 403 {"documentation_url": "https://docs.github.com/free-pro-team@latest/rest/overview/rate-limits-for-the-rest-api#about-secondary-rate-limits", "message": "You have exceeded a secondary rate limit. Please wait a few minutes before you try again. If you reach out to GitHub Support for help, please include the request ID A580:CFA2:150DF912:152B1A6B:6626[7](https://github.com/google/mtail/actions/runs/8785762325/job/24107012013#step:5:8)327."}
```

This just occurred in https://github.com/google/mtail/actions/runs/8785762325/job/24107012013

I don't know how to get more logs than this.
