### ISSUE TITLE
PR-less runs can't report comments

### ISSUE THREAD

**Issue by TWiStErRob** [EnricoMi/publish-unit-test-result-action#222] opened 2022-02-12 21:53 UTC
Hi, I have a [scheduled test run](https://github.com/TWiStErRob/net.twisterrob.healthcheck/blob/master/.github/workflows/Scheduled.yml)
which executes [this workflow](https://github.com/TWiStErRob/net.twisterrob.healthcheck/blob/b03644b6a69fd6c83789676fddb57ad1474aa610/.github/workflows/tests-run.yml#L56-L64) that uses your action.

For example see https://github.com/TWiStErRob/net.twisterrob.healthcheck/actions/runs/1832934306.
I don't understand why it doesn't happen every time, I didn't change anything for a while.

I just noticed that there are some issues:
![](https://user-images.githubusercontent.com/2906988/153729496-6e78efef-7312-4d7c-9439-9b64da2ad1cc.png)

<details><summary>log</summary>

```
Run EnricoMi/publish-unit-test-result-action@v1
/usr/bin/docker run --name ghcrioenricomipublishunittestresultactionv128_821dbf --label 7db2d7 --workdir /github/workspace --rm -e INPUT_CHECK_NAME -e INPUT_COMMENT_TITLE -e INPUT_REPORT_INDIVIDUAL_RUNS -e INPUT_TEST_CHANGES_LIMIT -e INPUT_FILES -e INPUT_GITHUB_TOKEN -e INPUT_GITHUB_RETRIES -e INPUT_COMMIT -e INPUT_FAIL_ON -e INPUT_TIME_UNIT -e INPUT_DEDUPLICATE_CLASSES_BY_FILE_NAME -e INPUT_HIDE_COMMENTS -e INPUT_COMMENT_ON_PR -e INPUT_COMMENT_MODE -e INPUT_COMPARE_TO_EARLIER_COMMIT -e INPUT_PULL_REQUEST_BUILD -e INPUT_EVENT_FILE -e INPUT_EVENT_NAME -e INPUT_CHECK_RUN_ANNOTATIONS -e INPUT_CHECK_RUN_ANNOTATIONS_BRANCH -e INPUT_SECONDS_BETWEEN_GITHUB_READS -e INPUT_SECONDS_BETWEEN_GITHUB_WRITES -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/net.twisterrob.healthcheck/net.twisterrob.healthcheck":"/github/workspace" ghcr.io/enricomi/publish-unit-test-result-action:v1.28
[20](https://github.com/TWiStErRob/net.twisterrob.healthcheck/runs/5165723653?check_suite_focus=true#step:8:20)[22](https://github.com/TWiStErRob/net.twisterrob.healthcheck/runs/5165723653?check_suite_focus=true#step:8:22)-02-12 06:04:30 +0000 - publish-unit-test-results -  INFO - reading /github/workspace/build/test-results/*/TEST-*.xml
2022-02-12 06:04:30 +0000 - publish -  INFO - publishing success results for commit b03644b6a69fd6c83789676fddb57ad1474aa610
2022-02-12 06:04:31 +0000 - publish -  INFO - created check https://github.com/TWiStErRob/net.twisterrob.healthcheck/runs/5165733182
2022-02-12 06:04:[31](https://github.com/TWiStErRob/net.twisterrob.healthcheck/runs/5165723653?check_suite_focus=true#step:8:31) +0000 - publish-unit-test-results - WARNING - Request GET /search/issues?q=type%3Apr+repo%3A%22TWiStErRob%2Fnet.twisterrob.healthcheck%22+b03644b6a69fd6c83789676fddb57ad1474aa610&per_page=100 failed: Forbidden
2022-02-12 06:04:31 +0000 - publish - WARNING - Request GET /search/issues?q=type%3Apr+repo%3A%22TWiStErRob%2Fnet.twisterrob.healthcheck%22+b03644b6a69fd6c83789676fddb57ad1474aa610&per_page=100 failed with 403: Forbidden
2022-02-12 06:04:31 +0000 - publish-unit-test-results -  INFO - There is no Retry-After given in the response header
2022-02-12 06:04:31 +0000 - publish-unit-test-results -  INFO - Response body indicates retry-able error
2022-02-12 06:04:31 +0000 - publish-unit-test-results - WARNING - Request GET /search/issues?q=type%3Apr+repo%3A%22TWiStErRob%2Fnet.twisterrob.healthcheck%22+b03644b6a69fd6c83789676fddb57ad1474aa610&per_page=100 failed: Forbidden
2022-02-12 06:04:31 +0000 - publish - WARNING - Request GET /search/issues?q=type%3Apr+repo%3A%22TWiStErRob%2Fnet.twisterrob.healthcheck%22+b03644b6a69fd6c83789676fddb57ad1474aa610&per_page=100 failed with 403: Forbidden
2022-02-12 06:04:31 +0000 - publish-unit-test-results -  INFO - There is no Retry-After given in the response header
2022-02-12 06:04:31 +0000 - publish-unit-test-results -  INFO - Response body indicates retry-able error
2022-02-12 06:04:[35](https://github.com/TWiStErRob/net.twisterrob.healthcheck/runs/5165723653?check_suite_focus=true#step:8:35) +0000 - publish-unit-test-results - WARNING - Request GET /search/issues?q=type%3Apr+repo%3A%22TWiStErRob%2Fnet.twisterrob.healthcheck%22+b0[36](https://github.com/TWiStErRob/net.twisterrob.healthcheck/runs/5165723653?check_suite_focus=true#step:8:36)44b6a69fd6c8[37](https://github.com/TWiStErRob/net.twisterrob.healthcheck/runs/5165723653?check_suite_focus=true#step:8:37)89676fddb57ad1474aa610&per_page=100 failed: Forbidden
2022-02-12 06:04:35 +0000 - publish - WARNING - Request GET /search/issues?q=type%3Apr+repo%3A%22TWiStErRob%2Fnet.twisterrob.healthcheck%22+b03644b6a69fd6c83789676fddb57ad1474aa610&per_page=100 failed with [40](https://github.com/TWiStErRob/net.twisterrob.healthcheck/runs/5165723653?check_suite_focus=true#step:8:40)3: Forbidden
2022-02-12 06:04:35 +0000 - publish-unit-test-results -  INFO - There is no Retry-After given in the response header
2022-02-12 06:04:35 +0000 - publish-unit-test-results -  INFO - Response body indicates retry-able error
2022-02-12 06:04:[44](https://github.com/TWiStErRob/net.twisterrob.healthcheck/runs/5165723653?check_suite_focus=true#step:8:44) +0000 - publish-unit-test-results - WARNING - Request GET /search/issues?q=type%3Apr+repo%3A%22TWiStErRob%2Fnet.twisterrob.healthcheck%22+b03644b6a69fd6c83789676fddb57ad1[47](https://github.com/TWiStErRob/net.twisterrob.healthcheck/runs/5165723653?check_suite_focus=true#step:8:47)4aa610&per_page=100 failed: Forbidden
2022-02-12 06:04:44 +0000 - publish - WARNING - Request GET /search/issues?q=type%3Apr+repo%3A%22TWiStErRob%2Fnet.twisterrob.healthcheck%22+b03644b6a69fd6c83789676fddb57ad1474aa610&per_page=100 failed with 403: Forbidden
2022-02-12 06:04:44 +0000 - publish-unit-test-results -  INFO - There is no Retry-After given in the response header
2022-02-12 06:04:44 +0000 - publish-unit-test-results -  INFO - Response body indicates retry-able error
2022-02-12 06:05:00 +0000 - publish-unit-test-results - WARNING - Request GET /search/issues?q=type%3Apr+repo%3A%22TWiStErRob%2Fnet.twisterrob.healthcheck%22+b03644b6a69fd6c83789676fddb57ad1474aa610&per_page=100 failed: Forbidden
2022-02-12 06:05:00 +0000 - publish - WARNING - Request GET /search/issues?q=type%3Apr+repo%3A%22TWiStErRob%2Fnet.twisterrob.healthcheck%22+b03644b6a69fd6c83789676fddb57ad1474aa610&per_page=100 failed with 403: Forbidden
2022-02-12 06:05:00 +0000 - publish-unit-test-results -  INFO - There is no Retry-After given in the response header
2022-02-12 06:05:00 +0000 - publish-unit-test-results -  INFO - Response body indicates retry-able error
Warning: Request GET /search/issues?q=type%3Apr+repo%3A%22TWiStErRob%2Fnet.twisterrob.healthcheck%22+b03644b6a69fd6c83789676fddb57ad1474aa610&per_page=100 failed with 403: Forbidden
Warning: Request GET /search/issues?q=type%3Apr+repo%3A%22TWiStErRob%2Fnet.twisterrob.healthcheck%22+b03644b6a69fd6c83789676fddb57ad1474aa610&per_page=100 failed with 403: Forbidden
Warning: Request GET /search/issues?q=type%3Apr+repo%3A%22TWiStErRob%2Fnet.twisterrob.healthcheck%22+b03644b6a69fd6c83789676fddb57ad1474aa610&per_page=100 failed with 403: Forbidden
Warning: Request GET /search/issues?q=type%3Apr+repo%3A%22TWiStErRob%2Fnet.twisterrob.healthcheck%22+b03644b6a69fd6c83789676fddb57ad1474aa610&per_page=100 failed with 403: Forbidden
Warning: Request GET /search/issues?q=type%3Apr+repo%3A%22TWiStErRob%2Fnet.twisterrob.healthcheck%22+b03644b6a69fd6c83789676fddb57ad1474aa610&per_page=100 failed with 403: Forbidden
```
</details>

This happens regardless of failure and it gets reported as annotations:
![image](https://user-images.githubusercontent.com/2906988/153729535-88601239-9eec-4dc7-8322-0ab6ab05702b.png)

I think the problem is that this scheduled run is happening on `master` which doesn't have a PR. Would it be possible to handle this case better?

1. recognize this and recommend some actions rather than retrying 5 times.
2. an option for changing the target where the comment goes.
   put the comment into the commit rather than the PR?
   i.e. open https://github.com/TWiStErRob/net.twisterrob.healthcheck/commit/b03644b6a69fd6c83789676fddb57ad1474aa610 and see the "comment section" at the bottom.

As a workaround for now I'll just disable with `comment_mode: off` to prevent this error, because there will never be a PR for master.

**Comment by EnricoMi** [comment] 2022-02-13 10:25
The problem is not that there is no PR in this case, but that the action cannot search for a PR (that is `Forbidden`). Even if there would be a PR, the same error would occur.

The question is: why is the `search` request failing with `Forbidden`? Also the `Response body indicates retry-able error` looks suspicious.

Could you please run the action with:
```yaml
with:
  root_log_level: DEBUG
  log_level: DEBUG
```

Can you also provide a link to the failing workflow run? There might be other insights from the logs.

**Comment by EnricoMi** [comment] 2022-02-13 12:51
Looking into the code, the log message `Response body indicates retry-able error` only occurs when the response contains either of the following strings:
- `api rate limit exceeded`
- `please wait a few minutes before you try again.`

This indicates that the cause of the `Forbidden` response is that the rate limit for the search API is exceeded. That limit is very low, only 30 requests per minute. So there might be other actions in your workflow that use the search API extensively and leave no requests for this action.

Can you please run the following action? This shows the full response message:
```yaml
uses: uses: EnricoMi/publish-unit-test-result-action/composite@master
```

**Comment by EnricoMi** [comment] 2022-02-13 16:41
I was able to reproduce the behaviour of the action with search rate limit exceeded. In #223 the behaviour is fixes in the sense that it waits until the rate limit is reset (>60s), so that only a single retry occurs. This will be merged into master soon. Release will happen later this month. Thanks for reporting this!

**Comment by TWiStErRob** [comment] 2022-02-13 17:00
Hmm, didn't have time to try yet, sorry. Do you still need me to run debug or master? Based on what you said it might've been a one off. Which is weird because it runs every single day for months now. I'll try to look what triggered that many requests around the same time.

**Closed** 2022-03-02 21:07 UTC
